version: '3.7'
services:
  nameapi:
    image: nameapi_image:latest
    deploy:
      replicas: 3
  
  classapi:
    image: classapi_image:latest
    deploy:
      replicas: 3

  raceapi:
    image: raceapi_image:latest
    deploy:
      replicas: 3
  
  server:
    image: server_image:latest
    deploy:
      replicas: 3
    ports:
    - published: 5000
      target: 5000